repos:
  - repo: https://github.com/dycw/pre-commit-hooks
    rev: 0.14.90
    hooks:
      - id: add-hooks
        args:
          - --ci-github
          - --description=Pre-commit hooks
          - --prettier
          - --python
          - --python-package-name-external=dycw-pre-commit-hooks
          - --python-package-name-internal=pre-commit-hooks
          - --repo-name=pre-commit-hooks
          - --shell
          - --toml
        priority: 10
      - id: setup-readme
        args:
          - --repo-name=pre-commit-hooks
          - --description=Pre-commit hooks
        priority: 20
      - id: setup-direnv
        args:
          - --python
        priority: 20
      - id: setup-pyright
        priority: 20
      - id: setup-pytest
        args:
          - --python-package-name-internal=pre-commit-hooks
        priority: 20
      - id: setup-ruff
        priority: 20
  - repo: builtin
    hooks:
      - id: check-case-conflict
        priority: 30
      - id: check-json
        priority: 30
      - id: check-json5
        priority: 30
      - id: check-merge-conflict
        priority: 30
      - id: check-symlinks
        priority: 30
      - id: check-toml
        priority: 30
      - id: check-xml
        priority: 30
      - id: check-yaml
        priority: 30
      - id: detect-private-key
        priority: 30
      - id: end-of-file-fixer
        priority: 20
      - id: fix-byte-order-marker
        priority: 20
      - id: mixed-line-ending
        args:
          - --fix=lf
        priority: 20
      - id: no-commit-to-branch
        priority: 30
      - id: trailing-whitespace
        priority: 20
  - repo: https://github.com/compwa/taplo-pre-commit
    rev: master
    hooks:
      - id: taplo-format
        args:
          - --option
          - indent_tables=true
          - --option
          - indent_entries=true
          - --option
          - reorder_keys=true
        priority: 30
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-illegal-windows-names
        priority: 30
      - id: destroyed-symlinks
        priority: 30
      - id: pretty-format-json
        args:
          - --autofix
        priority: 20
