repos:
  - hooks:
      - args:
          - --python-version=3.12
          - --ruff
        id: add-hooks
        priority: 10
      - args:
          - --python-version=3.12
        id: add-ruff-hooks
        priority: 10
      - id: check-versions-consistent
        priority: 20
    repo: https://github.com/dycw/pre-commit-hooks
    rev: 0.14.5
  - hooks:
      - id: check-added-large-files
        priority: 20
      - id: check-executables-have-shebangs
        priority: 20
      - id: check-json
        priority: 20
      - id: check-json5
        priority: 20
      - id: check-merge-conflict
        priority: 20
      - id: check-symlinks
        priority: 20
      - id: check-toml
        priority: 20
      - id: check-xml
        priority: 20
      - id: check-yaml
        priority: 20
      - id: detect-private-key
        priority: 20
      - id: end-of-file-fixer
        priority: 10
      - id: fix-byte-order-marker
        priority: 10
      - args:
          - --fix=lf
        id: mixed-line-ending
        priority: 10
      - id: no-commit-to-branch
        priority: 20
      - id: trailing-whitespace
        priority: 10
      - id: check-case-conflict
        priority: 20
    repo: builtin
  - hooks:
      - id: ruff-format
        priority: 10
      - id: ruff-check
        args:
          - --fix
        priority: 20
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
  - hooks:
      - id: check-illegal-windows-names
        priority: 20
      - id: destroyed-symlinks
        priority: 20
      - args:
          - --autofix
        id: pretty-format-json
        priority: 10
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
