repos:
  - repo: https://github.com/dycw/pre-commit-hooks
    rev: 0.14.85
    hooks:
      - id: add-hooks
        args:
          - --ci-github
          - --description=Pre-commit hooks
          - --prettier
          - --python
          - --python-package-name-external=dycw-pre-commit-hooks
          - --python-package-name-internal=pre-commit-hooks
          - --repo-name=pre-commit-hooks
          - --shell
          - --toml
