default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/dycw/pre-commit-hook-nitpick
    rev: 0.1.5
    hooks:
      - id: nitpick
        args: [--version, "3.14", --pyproject]
